-- Retire the original 21 MODEL-tab studio_styles rows (seeded in migration
-- 078) and replace with 8 finalized templates, per owner review 2026-09-18.
-- Reasons: (1) 21 near-duplicate scene backdrops collapsed into 7 distinct
-- looks + 1 social-post variant covering the same ground; (2) every old
-- MODEL prompt described a full standing pose with nothing to stop Kontext
-- inventing legs/trousers under a top-only garment (kurti/t-shirt) — fixed
-- at the code level in studio-shoot.ts (isTopOnlyGarment guard) and given
-- its own explicit template here (halfbody_top_indoor) for retailers who
-- want to pick it directly. PRODUCT-tab rows (ghost/hanger/flatlay/mannequin
-- etc.) are untouched — no complaint against those.
-- No FK from ProductPhoto to studio_styles (provenance is stored as JSON
-- metadata on the photo row), so deleting these rows does not affect any
-- already-generated photo.

DELETE FROM studio_styles WHERE slug IN (
  'blossom_atrium', 'boutique_showroom', 'runway', 'copper_diamond',
  'dupatta_motion', 'rooftop_golden', 'gradient_hero', 'heritage_library',
  'heritage_street', 'lakeside_deck', 'mall_concourse', 'pastel_gradient',
  'botanical_garden', 'seated_haveli_steps', 'studiomodel', 'teen_street',
  'tree_tunnel', 'editorial_vogue', 'male_with_car', 'male_with_bike',
  'kids_playing'
);

INSERT INTO studio_styles (id, slug, label, description, prompt, tab, status, plans, engine, audience, sort_order, updated_at) VALUES
  (gen_random_uuid()::text, 'studio_softbox_indoor', 'Indoor Studio Softbox', 'Clean seamless studio backdrop, eye-level softbox key light, full body', 'Place this garment on the model standing in a clean professional indoor studio with a seamless soft grey-beige backdrop, large softbox key light at eye level plus a subtle fill light, confident relaxed standing pose, soft natural grounding shadow. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved — no stretching, shortening or lengthening.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 0, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'home_mirror_selfie', 'Home Mirror Selfie', 'Casual full-length mirror selfie, warm home interior, influencer style', 'Place this garment on the model taking a casual full-length mirror selfie inside a warm, softly lit home interior — a large mirror, a cosy sofa or wooden console softly out of focus behind, a potted plant nearby, soft natural window light, phone held up in one hand in a relaxed influencer-style pose. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 1, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'golden_hour_outdoor', 'Golden Hour Outdoor', 'Warm sunset outdoor shoot, soft blurred greenery or street, full body', 'Place this garment on the model standing outdoors at warm golden-hour sunset, soft blurred greenery or an open street behind, gentle warm sun flare, relaxed natural full-body pose. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved with no warm-tone colour shift onto the fabric itself.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 2, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'catwalk_runway_motion', 'Catwalk Runway Motion', 'High-fashion runway walk, overhead spotlights, natural motion sway', 'Place this garment on the model walking confidently down a high-fashion catwalk runway, overhead spotlights, soft blurred audience bokeh behind, natural walking motion with a slight fabric sway. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved and stay sharp — only the background and pose show motion.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 3, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'editorial_closeup_rim', 'Editorial Close-Up', 'Chest-up editorial crop, dark backdrop, dramatic rim light', 'A tight editorial close-up of the model from the chest up, wearing this garment, seamless dark studio backdrop, dramatic rim light outlining the shoulders and a soft key light on the face, confident direct gaze. The garment''s exact colour, print, embroidery and fabric texture in frame are 100% preserved.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 4, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'marble_luxury_premium', 'Marble Premium Luxury', 'Elegant marble interior, warm ambient light, subtle gold accents', 'Place this garment on the model standing in an elegant marble-clad luxury interior, soft warm ambient light, subtle gold accents softly out of focus behind, poised confident stance. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 5, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'halfbody_top_indoor', 'Half-Body Top Shot (Kurti / T-Shirt)', 'Waist-up only — for standalone tops, no invented bottomwear or legs', 'Place this garment on the model in a clean indoor studio with soft even key light. Frame the shot from the head down to the hip — waist-up only. Do NOT show the model''s legs, hips-down, or feet, and do NOT add, invent or imply any trousers, palazzo, leggings, jeans or skirt that is not visible in the original product photo — this garment is a standalone top and must not be shown paired with a bottom that doesn''t exist in the source image. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved with no stretching or lengthening.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 6, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'social_post_square', 'Social Media Post Square', 'Bright lifestyle shot, centred full body, open space for logo/text', 'Place this garment on the model standing in a bright, clean lifestyle setting suited for a social media post — soft natural light, simple uncluttered background, centred full-body composition with even margins on both sides and clear open space above the head for a logo or text overlay. The garment''s exact colour, print, embroidery, fabric texture and original length are 100% preserved.', 'MODEL'::"StudioStyleTab", 'PUBLISHED'::"StudioStyleStatus", ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::text[], 7, CURRENT_TIMESTAMP);
