-- Generated by scripts/delete-test-retailers.ts (2026-08-08T17:13:01.286Z)
-- Deletes ONLY these retailer accounts + all their data: 919898989898, 919999988888, 919999999999, 913131313131, 911313131313
-- Run in Supabase SQL Editor (superuser). One transaction — any failure rolls back everything.

BEGIN;

SET app.allow_hard_delete = 'true';

-- Reset storefront pointers before collections disappear
UPDATE retailers SET storefront_collection_id = NULL
WHERE id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');

-- ── Children first (FK-safe order) ──
DELETE FROM product_photos        WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM product_spin_frames   WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM product_variants      WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM product_embeddings    WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM collection_products   WHERE collection_id IN (SELECT id FROM collections WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7'));
DELETE FROM collection_views      WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM collection_enquiries  WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM customer_interactions WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM customer_measurements WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM customer_fashion_dna  WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM order_items           WHERE order_id IN (SELECT id FROM orders WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7'));
DELETE FROM subscription_payments WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM size_chart_rows       WHERE size_chart_id IN (SELECT id FROM size_charts WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7'));
DELETE FROM training_photo_consents WHERE try_on_job_id IN (SELECT id FROM try_on_jobs WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7'));
DELETE FROM try_on_usage_logs     WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM try_on_jobs           WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');

-- ── Parents ──
DELETE FROM products             WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM collections          WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM customers            WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM orders               WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM subscriptions        WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM size_charts          WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM staff                WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM store_sections       WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM product_categories   WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM product_attributes   WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM support_tickets      WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM retailer_payment_accounts WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM retailer_limit_overrides  WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM usage_counters       WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM quota_addon_purchases WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM ai_usage_logs        WHERE retailer_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');
DELETE FROM audit_logs           WHERE actor_id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');

-- ── The accounts themselves ──
DELETE FROM retailers WHERE id IN ('cmsfpz6sj000cch3dglib890t', 'cmrlx3hog0000zfnjea54ic6z', 'cmscud4sk000cfs0resf5e7qu', 'cmrf020c6000z13osff9jm2w2', 'cmsfuqpha0000fegprbvs33d7');

COMMIT;

-- Verify: expect 0 rows for each phone
SELECT phone, count(*) AS remaining FROM retailers
WHERE phone IN ('9898989898', '9999988888', '9999999999', '3131313131', '1313131313')
GROUP BY phone;
