-- F-032 option matrix: seed the owner's 27 Product Only / Model Only styles
-- (docs/tasks/pending/studio-shoot-option-matrix.md §14, rollout task 2.3).
--
-- ADDITIVE AND INVISIBLE. Every row is inserted as DRAFT, so GET /products/studio-styles
-- and POST /studio-shoot (both require status = 'PUBLISHED') do not see them until the
-- owner publishes each row in Admin -> Studio Styles after a real-photo bench. Nothing
-- existing is changed or retired here: retiring the legacy catalog while the new rows are
-- still DRAFT would leave retailers with an empty picker. Hide the legacy rows from the
-- admin UI (or a follow-up migration) once the new ones are published (rollout 2.4/2.7).
--
-- * slug = lower-cased style id ('ps-03', 'mi-02', 'mo-05'). poolsForSlug() in
--   @kanchuki/shared and the mobile Indoor/Outdoor grouping key off this convention.
-- * prompt keeps the {{Pool}} tokens; the studio-shoot job resolves one pick per
--   generation from the shared pools (the DB has no column for pools).
-- * engine NULL = default cascade; per-style routing waits on bench run 2 (rollout 2.5).
-- * plans = all three: AI Studio is gated by the STUDIO_SHOOT quota, not by plan.
-- * ON CONFLICT DO NOTHING: re-running never overwrites an admin's edits.
-- * Generated by scripts/gen-studio-option-matrix-seed.mjs from packages/shared.
--
-- Rollback: DELETE FROM studio_styles WHERE slug ~ '^(ps|mi|mo)-[0-9]{2}$' AND status = 'DRAFT';
-- (never delete a PUBLISHED row that has usage_count > 0 — hide it instead).

INSERT INTO studio_styles (id, slug, label, description, prompt, tab, status, plans, engine, audience, sort_order, updated_at) VALUES
  (gen_random_uuid()::text, 'ps-03', $kp$Luxury Studio Product$kp$, $kp$Headless dress form on a pedestal, warm gold arch, softbox light$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Remove the original hanger, person, model, mannequin, or existing display method. Re-present the garment as a premium product display on a true headless torso dress form positioned on an elegant pedestal. The dress form has no head, face, ears, hair, skin, facial features, or human head shape; only the torso, shoulders and short neck/collar area are visible. This is a product display, not clothing worn by a person.

Place the garment inside a sophisticated luxury fashion studio featuring a warm gold architectural arch in the background and an elegant premium pedestal beneath the garment. Use refined warm softbox lighting with controlled highlights, realistic fabric shadows, dimensional depth and premium commercial composition. Show the complete garment in a centered, full-length, front-facing view with realistic fabric drape, accurate proportions, crisp textile detail and photorealistic high-end fashion-commerce quality.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the product presentation, environment, composition, pedestal and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 100, now()),
  (gen_random_uuid()::text, 'ps-04', $kp$Editorial Studio Product$kp$, $kp$Headless dress form against a grey editorial wall with window light$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Remove the original hanger, person, model, mannequin, or existing display method. Re-present the garment as a premium product display on a true headless torso dress form. The dress form has no head, face, ears, hair, skin, facial features, or human head shape; only the torso, shoulders and short neck/collar area are visible. This is a product display, not clothing worn by a person.

Place the garment in a sophisticated grey editorial studio with a textured grey wall, clean light floor, minimal architectural styling and elegant white decorative vases on simple pedestals. Use natural side window light creating distinct soft diagonal window shadows across the wall and floor, warm daylight highlights and gentle natural contrast. Show the complete garment in a centered, full-length, front-facing composition with realistic fabric drape, accurate proportions, detailed textile texture, refined editorial styling and premium photorealistic commercial quality.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the product presentation, environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 101, now()),
  (gen_random_uuid()::text, 'ps-05', $kp$Color Background$kp$, $kp$Clean solid blue backdrop, garment only$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Present the complete garment as a premium product display against a clean, seamless flat-color backdrop. Use a sophisticated solid blue studio background with no gradients, patterns, textures, architectural elements, furniture, props, people, models, or mannequins. Center the complete garment in a full-length front-facing composition with generous clean space around it.

Use professional softbox lighting with even illumination, controlled highlights, realistic fabric shadows, accurate color reproduction, crisp textile detail and a polished commercial fashion-catalog appearance.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the presentation, background, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 102, now()),
  (gen_random_uuid()::text, 'ps-06', $kp$Premium Product Shot$kp$, $kp$Full-length product shot on a warm beige and cream backdrop$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Present the complete garment as a premium full-length fashion product display against a warm sophisticated luxury backdrop. Use an elegant warm beige and cream environment with subtle architectural depth, refined decorative styling and soft premium visual character. Keep the entire garment fully visible from top to bottom in a centered front-facing composition. This is a complete product shot, not a close-up or detail photograph.

Use natural daylight with soft directional illumination, gentle highlights, realistic fabric shadows, dimensional depth, accurate textile texture and refined high-end fashion-commerce photography.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the product presentation, environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 103, now()),
  (gen_random_uuid()::text, 'ps-07', $kp$Flat Lay$kp$, $kp$Top-down flat lay with fresh flowers and jewellery$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Arrange the complete garment as a premium flat-lay composition on a clean elegant surface, viewed directly from above. Lay the garment naturally and fully visible, maintaining its original construction, proportions and recognizable arrangement. Surround it with tasteful fresh flowers and carefully arranged fashion jewellery as supporting props, creating a refined boutique flat-lay aesthetic without covering or obscuring the garment.

Use bright natural daylight with soft directional shadows, realistic fabric texture, crisp embroidery and print detail, balanced composition and premium editorial product photography.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add or remove any garment detail. Props must never cover or alter the product.

Change only the product arrangement, surface, props, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 104, now()),
  (gen_random_uuid()::text, 'ps-08', $kp$Folded Boutique Fold$kp$, $kp$Single boutique fold on a rattan tray$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Present the garment as a single elegant boutique fold placed neatly on a natural rattan tray. Use one clearly defined folded presentation only, with the garment arranged carefully so its important fabric, print, embroidery and border details remain visible. Create a refined boutique merchandising composition with a warm neutral surface and subtle natural styling.

Use soft natural daylight with gentle directional shadows, realistic textile texture, accurate colors, crisp embroidery detail and premium boutique product photography.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions and construction. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Use exactly one folded garment presentation on the rattan tray. Do not create multiple folds or stacks. Change only the presentation, surface, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 105, now()),
  (gen_random_uuid()::text, 'ps-09', $kp$Hanger Boutique$kp$, $kp$Wooden hanger on a boutique rail$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Display the complete garment naturally on a premium wooden hanger within an elegant boutique setting. Use a refined boutique rail or sophisticated wall-mounted clothing rail as the presentation structure, with the garment centered and fully visible from top to bottom. Keep the environment warm, clean and professionally styled without people or models.

Use soft natural daylight entering the boutique space, creating gentle directional shadows, realistic fabric drape, accurate garment proportions, crisp textile detail and premium fashion-retail photography.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the hanger presentation, boutique environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 106, now()),
  (gen_random_uuid()::text, 'ps-10', $kp$Boutique Fold$kp$, $kp$Two-stack boutique fold on a wooden table$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Present the garment as a premium boutique two-stack folded display arranged neatly on a sophisticated wooden table. Create exactly two coordinated folded layers/stacks of the same garment presentation, arranged naturally for luxury retail merchandising. Keep important embroidery, print, borders and fabric details visible and unobstructed.

Use soft natural daylight with warm directional illumination, realistic fabric shadows, detailed textile texture and refined boutique-commerce photography. Create an elegant, warm and premium retail atmosphere.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions and construction. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove or invent any garment detail.

Use exactly a two-stack folded presentation on the wooden table. Do not create a single fold, flat lay or additional stacks. Change only the presentation, table, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 107, now()),
  (gen_random_uuid()::text, 'ps-11', $kp$Table Display$kp$, $kp$Draped over the edge of a wooden table$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Present the garment naturally laid and elegantly draped across a premium wooden table. Allow part of the garment to flow naturally over the table edge while keeping the main product clearly visible and recognizable. Create a refined boutique merchandising scene with subtle luxury decor and an uncluttered composition.

Use soft natural daylight with realistic directional shadows, natural fabric folds, accurate textile texture, crisp embroidery and print detail, balanced composition and premium commercial product photography.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the product arrangement, table environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 108, now()),
  (gen_random_uuid()::text, 'ps-12', $kp$Pedestal Display$kp$, $kp$Round pedestal under an architectural arch$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Present the complete garment as a premium product display on an elegant round pedestal inside a sophisticated architectural studio. Place the garment centrally beneath a large refined arch structure in the background, creating a clean luxury fashion presentation. Keep the complete garment fully visible from top to bottom in a centered front-facing composition.

Use professional softbox lighting with controlled highlights, realistic fabric shadows, dimensional depth, crisp textile detail and polished high-end commercial fashion photography. Maintain a refined warm neutral luxury palette.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the product presentation, pedestal, architectural environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 109, now()),
  (gen_random_uuid()::text, 'ps-13', $kp$Product Commercial Shot$kp$, $kp$Pure white marketplace shot with a grounding shadow$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Create a clean professional commercial product photograph of the complete garment against a seamless pure white background. Present the entire garment fully visible from top to bottom in a centered front-facing composition with clean edges and generous white space. Keep the scene completely free from decorative props, furniture, people, models and distracting elements.

Use high-key commercial lighting with bright even exposure and a controlled distinct hard grounding shadow beneath and behind the product. Maintain crisp garment edges, accurate color reproduction, sharp textile detail and clean marketplace-ready product photography.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Change only the product presentation, white background, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 110, now()),
  (gen_random_uuid()::text, 'ps-14', $kp$Creative Display Product Composition$kp$, $kp$Decorative frame with florals and luxury props$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Create a premium creative product composition featuring the complete garment as the central subject. Display the garment within an elegant decorative frame structure surrounded by tasteful fresh florals and carefully selected luxury props. Arrange the elements as a sophisticated fashion campaign composition while keeping the garment clearly visible, dominant and unobstructed.

Use professional softbox lighting with refined controlled highlights, realistic shadows, dimensional depth and crisp textile detail. Create a polished editorial-commercial aesthetic with balanced composition and premium visual hierarchy.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Props and decorative elements must support the composition without covering, modifying or replacing any part of the garment. Change only the presentation, props, environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 111, now()),
  (gen_random_uuid()::text, 'ps-15', $kp$Social Media Commerce$kp$, $kp$Bright high-key social-commerce look, no text$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Create a premium social-commerce product photograph with the complete garment as the central subject. Use a bright, clean high-key studio environment with a polished modern commercial background and a visually engaging but uncluttered composition optimized for social-media product presentation. Keep the entire garment fully visible from top to bottom, centered and immediately recognizable.

Use bright high-key lighting with clean exposure, crisp garment edges, realistic textile texture, subtle controlled shadows and strong product clarity. Create a polished, modern, scroll-stopping commercial image without adding any written content.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

Do not generate text, words, letters, logos, captions, slogans, prices, promotional messages, watermarks or typography anywhere in the image. Change only the product presentation, environment, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 112, now()),
  (gen_random_uuid()::text, 'ps-16', $kp$Editorial Product Display$kp$, $kp$Garment styled with accessories in an editorial interior$kp$, $kp$Replace the existing product presentation completely while preserving the uploaded garment itself exactly.

Create ONE premium editorial product photograph featuring the uploaded garment as the hero product, in this environment: {{Environment}}, using this presentation: {{Presentation}}. This is a product-focused image, not a model portrait: no person, no model and no mannequin. Arrange the garment and these accessories into a sophisticated, commercially usable bundled fashion presentation: {{Styling}}. Accessories complement the garment without covering, altering or competing with it.

Use beautiful natural light from a large window or open architectural source, with soft directional illumination, gentle realistic shadows, subtle highlights, accurate colors and authentic fabric texture. Create a refined editorial atmosphere with natural depth and premium photographic composition.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly as shown, including its original color, fabric, print, embroidery, motifs, neckline, sleeves, borders, length, texture, stitching, proportions, construction, dupatta and every visible design detail. Do not redesign, recolor, simplify, stretch, shorten, reshape, distort, replace, add, remove, duplicate or invent any garment detail.

BUNDLED LOOK RULE: accessories are separate styling props only. They must never become part of the garment, change its design, hide embroidery or details, or read as additional clothing. One garment, one presentation, one styling arrangement. No text, labels, logos or watermark. Change only the presentation, environment, styling props, composition and lighting.$kp$, 'PRODUCT', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 113, now()),
  (gen_random_uuid()::text, 'mi-01', $kp$Product Composition$kp$, $kp$Model in a styled indoor studio with coordinated props$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

ENVIRONMENT: {{Scene}}.
POSE: {{Pose}}.

Place the model in the selected sophisticated indoor fashion environment with tasteful coordinated props such as a small handbag, appropriate footwear, flowers, a mirror, a premium chair, a side table or subtle boutique décor. Props complement the outfit and never cover important garment details.

Use professional softbox lighting: bright clean exposure, gentle fill, soft natural shadows, accurate colors and crisp embroidery/print detail.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 200, now()),
  (gen_random_uuid()::text, 'mi-02', $kp$Courtyard$kp$, $kp$Model in a refined daytime courtyard$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: {{Pose}}.

Courtyard only. Place the model naturally in a refined courtyard during daytime, with elegant architectural details such as arches, carved stone, columns, warm neutral walls, greenery, flowers, subtle traditional décor or premium outdoor furniture. Keep the courtyard attractive but secondary to the garment.

Use natural daylight with soft directional sunlight, gentle ambient fill, realistic soft shadows and clean exposure. Preserve accurate garment colors and crisp fabric, embroidery and print detail, with realistic depth and a natural outdoor atmosphere.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 201, now()),
  (gen_random_uuid()::text, 'mi-04', $kp$Boutique$kp$, $kp$Model inside a designer boutique$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

ENVIRONMENT: {{Scene}}.
POSE: {{Pose}}.

Place the model naturally inside the selected boutique with tasteful boutique elements such as curated clothing racks, elegant shelving, display tables, mirrors, subtle Indian décor, premium hangers, folded garments, handbags or minimal accessories. Props stay secondary and never hide or compete with the garment.

Use professional softbox lighting: large diffused key light, gentle fill, controlled highlights, accurate exposure, realistic soft grounding shadows and crisp textile detail. Maintain natural skin tones and accurate garment colors.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 202, now()),
  (gen_random_uuid()::text, 'mi-05', $kp$Shopping Mall$kp$, $kp$Model in a premium shopping mall$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

ENVIRONMENT: {{Scene}}.
POSE: {{Pose}}.

Place the model naturally inside the selected shopping-mall environment, using elegant storefronts, glass displays, polished flooring, escalators, architectural details and tasteful retail displays as background elements. Keep the environment sophisticated but secondary to the garment.

Use high-key commercial lighting with bright, clean, evenly diffused illumination, soft controlled shadows, accurate exposure, crisp textile detail and realistic depth. The garment must remain clearly visible from the chosen camera angle.

BLANK SIGNAGE ONLY: any visible storefront signs, banners, digital screens, posters or promotional panels must be completely blank, clean surfaces. No readable text, letters, numbers, brand names, logos, symbols or advertisements anywhere in the scene.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 203, now()),
  (gen_random_uuid()::text, 'mi-08', $kp$Social Commerce$kp$, $kp$Social launch post: model, detail panels and a short headline$kp$, $kp$Launch theme: {{Theme}}.

Create ONE premium social-media fashion launch post introducing the uploaded garment as a NEW PRODUCT / NEW DESIGN. It must look completely different from a traditional editorial product photo or e-commerce image.

FIXED COMPOSITION:
- LEFT 55–65%: one fashion model wearing the exact uploaded garment, full or three-quarter length, confident natural pose, complete outfit clearly visible.
- RIGHT 35–45%: 2–3 close-up detail panels from the SAME garment: (1) neckline / upper embroidery, (2) main embroidery / fabric texture, (3) bottom hem / border / sleeve finishing.

Detail panels must show real garment areas exactly as they appear in the reference — no invented details.

SOCIAL DESIGN: add tasteful premium fashion-brand typography and minimal graphic elements. Use only short messaging from this list: NEW ARRIVAL, NEW DESIGN, PREMIUM EMBROIDERY, NEW SEASON, DESIGNER PICK. Spell every word exactly; no other text, no prices, no brand names. Clean modern typography, elegant spacing, subtle lines/shapes, strong visual hierarchy. Never cover the model's face or important garment details.

STYLING: a sophisticated high-key fashion background with tasteful jewellery, earrings, bangles, handbag, perfume, shoes, flowers or other premium accessories. Props remain secondary to the garment.

LIGHTING: bright high-key commercial lighting, soft diffused illumination, clean highlights, realistic shadows, accurate colors and crisp textile/macro detail.

STRICT GARMENT PROTECTION: the uploaded garment is the ABSOLUTE SINGLE SOURCE OF TRUTH. Preserve exact color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, added embroidery, altered print, changed neckline/sleeves, invented details, removal, stretching, shortening or distortion.

IMPORTANT: this must look like a premium Instagram/Facebook fashion launch announcement, combining model + close-up product storytelling + graphic information + lifestyle styling. Not a simple catalogue photo, flat lay, mannequin shot or standard editorial image. Show the garment from the front only; never show or invent the back.

FINAL: Model left • 2–3 detail panels right • New-product launch aesthetic • High-key • Premium typography • Jewellery/lifestyle props • Exact garment preservation • No duplicate garments • No watermark.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 204, now()),
  (gen_random_uuid()::text, 'mi-10', $kp$Grey Background Studio$kp$, $kp$Model on a plain grey studio backdrop$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: {{Pose}}.

Plain seamless medium-light grey studio backdrop, clean and distraction-free, with a subtle tonal gradient and a smooth floor transition. No furniture, décor, artwork, shelves or unnecessary props. Show the complete outfit from head to toe whenever possible; no mannequin.

Use professional softbox lighting: large diffused key light, subtle fill, soft natural grounding shadow, controlled highlights, accurate exposure, realistic skin tones and crisp fabric/detail visibility.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 205, now()),
  (gen_random_uuid()::text, 'mo-01', $kp$Modern Street$kp$, $kp$Model on a stylish urban street$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: a stylish real urban street with sidewalks, buildings and street architecture.
SCENE LIGHTING: Daylight.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 300, now()),
  (gen_random_uuid()::text, 'mo-02', $kp$Cafe$kp$, $kp$Model at an outdoor cafe$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: a clearly recognizable outdoor café with tables, chairs and café surroundings. Signage must be blank.
SCENE LIGHTING: Natural Light.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 301, now()),
  (gen_random_uuid()::text, 'mo-03', $kp$Terrace$kp$, $kp$Model on an open terrace$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: an open terrace with visible railing, outdoor flooring and surrounding architecture.
SCENE LIGHTING: Daylight.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 302, now()),
  (gen_random_uuid()::text, 'mo-04', $kp$Balcony$kp$, $kp$Model on an open balcony$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: a clearly recognizable open balcony with visible railing and exterior surroundings. Never make it look like an indoor room.
SCENE LIGHTING: Natural Light.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 303, now()),
  (gen_random_uuid()::text, 'mo-05', $kp$Beach$kp$, $kp$Model on a beach$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: a beach with visible sand, shoreline, ocean/water and open sky.
SCENE LIGHTING: Daylight.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 304, now()),
  (gen_random_uuid()::text, 'mo-06', $kp$Poolside$kp$, $kp$Model beside a swimming pool$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: a poolside with a clearly visible swimming pool, water and pool deck.
SCENE LIGHTING: Daylight.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 305, now()),
  (gen_random_uuid()::text, 'mo-07', $kp$Tropical Resort$kp$, $kp$Model at a tropical resort$kp$, $kp$Create ONE premium commercial fashion photograph featuring one model wearing the uploaded garment. The uploaded garment is the single source of truth and must remain the primary visual focus. Keep the garment completely visible and unobstructed. Realistic anatomy, natural posture, realistic skin and hair, minimal elegant styling. Walking poses are toward the camera, never away.

STRICT GARMENT PROTECTION: Preserve the uploaded garment exactly — original color, fabric, texture, print, embroidery, motifs, neckline, sleeves, borders, trims, buttons, stitching, embellishments, proportions, length, silhouette, construction, dupatta/scarf, bottom piece and every visible detail. No redesign, recoloring, simplification, stretching, shortening, distortion, replacement, removal, duplication or invented details. Fit the exact garment naturally to the model without changing its construction. Show the garment from the front only; never show or invent the back.

FINAL: One model • One complete outfit • One environment • One natural fashion pose • No collage • No duplicate model • No additional featured clothing • No labels • No logos • No watermark • No readable text.

PRIORITY: Exact Garment → Natural Fit → Garment Visibility → Lighting → Model Presentation → Environment.

POSE: one natural, elegant fashion pose appropriate for the selected environment (standing, relaxed or gentle walking; walking is toward the camera).

SCENE ACCURACY: the selected environment must be immediately recognizable as its category. Never substitute a generic outdoor scene, garden, indoor room, studio, showroom or unrelated location.

LIGHTING: use only the lighting specified for the scene — Daylight or Natural Light. Realistic outdoor illumination, accurate colors, soft natural shadows and detailed fabric rendering. No studio softbox, flash, sunset, golden hour, evening or night lighting.

COMPOSITION: one full-body or three-quarter fashion photograph. The complete garment stays clearly visible and unobstructed. Show enough of the environment to establish the location while keeping the garment the visual hero.

SCENE: a tropical resort with recognizable resort architecture, tropical plants, palms and landscaped surroundings.
SCENE LIGHTING: Natural Light.$kp$, 'MODEL', 'DRAFT', ARRAY['STARTER','GROWTH','PRO']::"SubscriptionPlan"[], NULL, ARRAY[]::TEXT[], 306, now())
ON CONFLICT (slug) DO NOTHING;
